# Generated by Django 5.0 on 2023-12-16 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_contact_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='likelihood',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='spam_likelihood',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.DeleteModel(
            name='SpamReport',
        ),
    ]
