# Generated by Django 5.0 on 2023-12-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_contact_likelihood_alter_contact_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('spam_likelihood', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='likelihood',
            new_name='spam_likelihood',
        ),
    ]
