# Generated by Django 5.0 on 2023-12-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_spam_rename_likelihood_contact_spam_likelihood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='spam_likelihood',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='spam_likelihood',
            field=models.IntegerField(default=0),
        ),
    ]
